"""Change best_answer_id name

Revision ID: 05f1e9eeb1b9
Revises: 36112ca3df29
Create Date: 2020-06-14 17:06:41.633070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05f1e9eeb1b9'
down_revision = '36112ca3df29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('best_answer', sa.Integer(), nullable=True))
    op.drop_column('questions', 'best_answer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('best_answer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('questions', 'best_answer')
    # ### end Alembic commands ###
