"""Add bio field to User

Revision ID: 449088afffe0
Revises: 53d1e4e78465
Create Date: 2021-08-28 15:09:01.836673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '449088afffe0'
down_revision = '53d1e4e78465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
