"""change profile user attr to avatar

Revision ID: 4d21f9c935b8
Revises: dbcb68acc906
Create Date: 2021-01-25 17:11:58.173692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d21f9c935b8'
down_revision = 'dbcb68acc906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.String(), nullable=True))
    op.drop_column('users', 'profile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###
