"""rename password column to _password

Revision ID: 5beff4de6312
Revises: 58845ec9c95f
Create Date: 2022-03-21 06:24:16.994779

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5beff4de6312'
down_revision = '58845ec9c95f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password', new_column_name='_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.drop_column('users', '_password')
    # ### end Alembic commands ###
