"""Add accepted_answer column to Questions

Revision ID: 79271203e19b
Revises: 95032549004c
Create Date: 2021-01-26 17:11:11.242136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79271203e19b'
down_revision = '95032549004c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('accepted_answer', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'questions', 'answers', ['accepted_answer'], ['id'])
    op.drop_column('questions', 'best_answer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('best_answer', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'accepted_answer')
    # ### end Alembic commands ###
