"""Add created_at column

Revision ID: 8798215296f4
Revises: 92cb0795b884
Create Date: 2020-06-10 00:02:12.160501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8798215296f4'
down_revision = '92cb0795b884'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('questions', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'created_at')
    op.drop_column('answers', 'created_at')
    # ### end Alembic commands ###
