"""enhance accepted_answer foreign key

Revision ID: 8cd0c53718ec
Revises: 79271203e19b
Create Date: 2021-07-09 15:18:25.819968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd0c53718ec'
down_revision = '79271203e19b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('questions_accepted_answer_fkey', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'answers', ['accepted_answer'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_accepted_answer_fkey', 'questions', 'answers', ['accepted_answer'], ['id'])
    # ### end Alembic commands ###
