"""Add role column to users table

Revision ID: aee1b61601a9
Revises: b1b380f04f9d
Create Date: 2021-01-17 22:34:57.449827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aee1b61601a9'
down_revision = 'b1b380f04f9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles_permissions', 'permission_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('roles_permissions', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('users', sa.Column('role', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'roles', ['role'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role')
    op.alter_column('roles_permissions', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('roles_permissions', 'permission_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
