"""Change role colmn name to role_id

Revision ID: dbcb68acc906
Revises: aee1b61601a9
Create Date: 2021-01-17 22:42:22.980718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbcb68acc906'
down_revision = 'aee1b61601a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=False))
    op.drop_constraint('users_role_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_role_fkey', 'users', 'roles', ['role'], ['id'])
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###
