"""add users table

Revision ID: eba22c4d657e
Revises: 05f1e9eeb1b9
Create Date: 2021-01-17 14:29:38.339119

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'eba22c4d657e'
down_revision = '05f1e9eeb1b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=60), nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), nullable=False),
    sa.Column('password', sa.LargeBinary(), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('job', sa.VARCHAR(length=50), nullable=True),
    sa.Column('profile', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    op.execute('ALTER TABLE answers ALTER COLUMN user_id TYPE INTEGER USING user_id::integer')
    op.execute('ALTER TABLE questions ALTER COLUMN user_id TYPE INTEGER USING user_id::integer')
    op.create_foreign_key(None, 'answers', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'questions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.drop_table('users')
    # ### end Alembic commands ###
