"""Change body to content

Revision ID: 36112ca3df29
Revises: 0398aabca5eb
Create Date: 2020-06-10 16:41:26.527556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36112ca3df29'
down_revision = '0398aabca5eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('content', sa.String(), nullable=False))
    op.drop_column('answers', 'body')
    op.add_column('questions', sa.Column('content', sa.String(), nullable=False))
    op.drop_column('questions', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('questions', 'content')
    op.add_column('answers', sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('answers', 'content')
    # ### end Alembic commands ###
